#!/bin/sh

data="word0 word1 word2\rword3 word4\r"
/bin/echo -ne "$data" > t/cr.in
/bin/echo -ne "$data" | tr '\r' '\n' > t/cr.out

data="word0 word1 word2\r\nword3 word4\r\n"
/bin/echo -ne "$data" > t/crlf.in
/bin/echo -ne "$data" | tr -d '\r' > t/crlf.out

data="word0 word1 word2\nword3 word4\n"
/bin/echo -ne "$data" > t/lf.in
cp t/lf.in t/lf.out

data="word0 word1 word2\r\rword3 word4\r\r"
/bin/echo -ne "$data" > t/cr2x.in
/bin/echo -ne "$data" | tr '\r' '\n' > t/cr2x.out

perl -e 'print qq}word\\\r\rpalabra\r\\\r}'  > t/crescaped.in
perl -e 'print qq}word\\\r\npalabra\n\\\r}'  > t/crescaped.out

perl -e 'print qq}\r\\\r}' > t/one-cr-esc.in
perl -e 'print qq}\n\\\r}' > t/one-cr-esc.out

perl -e 'print qq}\015\\\r}' > t/one-oct-cr-esc.in
perl -e 'print qq}\012\\\r}' > t/one-oct-cr-esc.out
