.PHONY: clean test

DESTDIR=/usr/local/bin

prog=unixlf
testprog=runtests

$(prog): main.c
	cc -o $@ $<

tests: $(prog) $(testprog)
	./maketests
	./runtests

$(testprog): runtests.txt
	sed "s}PROG=$$}#DO NOT EDIT THIS FILE!\nPROG=./$(prog)}" < $< > $@
	chmod +x $@

install: $(prog)
	install $(prog) $(DESTDIR)

clean:
	$(RM) *~  t/*.tmp $(prog) $(testprog)
